include: package:pedantic/analysis_options.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    
# http://dart-lang.github.io/linter/lints
linter:
  rules:
    always_declare_return_types: true
    annotate_overrides: true
    
