name: oagnodes
description: >-
  A collection of classes to create and manage behavior trees and finite
  state machines.
version: 0.0.7
repository: https://github.com/oag-lcmc/dart_oagnodes

environment:
  sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
